Desktop/ter_proximity/src/Entity/Admin.php
<?php

namespace App\Entity;

use App\Repository\AdminRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdminRepository::class)
 */
class Admin
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Service::class, mappedBy="Admin")
     */
    private $services;

    /**
     * @ORM\OneToMany(targetEntity=TypeService::class, mappedBy="admin")
     */
    private $typeServices;

    public function __construct()
    {
        $this->services = new ArrayCollection();
        $this->typeServices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return Collection|Service[]
     */
    public function getServices(): Collection
    {
        return $this->services;
    }

    public function addService(Service $service): self
    {
        if (!$this->services->contains($service)) {
            $this->services[] = $service;
            $service->setAdmin($this);
        }

        return $this;
    }

    public function removeService(Service $service): self
    {
        if ($this->services->removeElement($service)) {
            // set the owning side to null (unless already changed)
            if ($service->getAdmin() === $this) {
                $service->setAdmin(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|TypeService[]
     */
    public function getTypeServices(): Collection
    {
        return $this->typeServices;
    }

    public function addTypeService(TypeService $typeService): self
    {
        if (!$this->typeServices->contains($typeService)) {
            $this->typeServices[] = $typeService;
            $typeService->setAdmin($this);
        }

        return $this;
    }

    public function removeTypeService(TypeService $typeService): self
    {
        if ($this->typeServices->removeElement($typeService)) {
            // set the owning side to null (unless already changed)
            if ($typeService->getAdmin() === $this) {
                $typeService->setAdmin(null);
            }
        }

        return $this;
    }

}

Desktop/ter_proximity/src/Controller/DefaultController.php
<?php

namespace AppBundle\Controller;

namespace App\Controller;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use App\Entity\Pin;
use App\Entity\User;
use App\Repository\PinRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\ParameterBag;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use App\Entity\Fournisseur;
use App\Form\FournisseurType;
use App\Entity\TypeService;
use App\Form\GenreType;

use App\Form\ServiceType;
use App\Entity\Calendrier;
use App\Form\CalendrierType;
use App\Form\SearchByDayType;
use App\Form\SearchByIntervallType;
use App\Entity\Jour;
use App\Form\JourType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use App\Entity\Reservation;
use App\Form\ReservationType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateIntervalType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\HttpFoundation\JsonResponse;
use App\Controller\Environment;
use App\Repository\ReservationRepository;
use App\Repository\NotesRepository;
use App\Entity\Notes;
use Symfony\Component\Security\Guard\GuardAuthenticatorHandler;
use SymfonyCasts\Bundle\VerifyEmail\Exception\VerifyEmailExceptionInterface;
use App\Security\LoginFormAuthenticator;
use App\Security\EmailVerifier;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\Mime\Address;
use Symfony\Component\Mime\Email;
use Symfony\Component\Mailer\MailerInterface;
use App\Entity\Service;
use Symfony\Component\Form\FormTypeInterface;
class DefaultController extends AbstractController
{
   /**
     * @Route("/recherche", name="app_searche",methods={"Get","POST"})
     */
   /* public function indexAction(Request $request):  Response
    {//fonction de reserche de ville
       $manager = $this->getDoctrine()->getManager();
       $services= new Service();

         $form = $this->createForm(Service::class, $services);
         $form->handleRequest($request);

        $kw = $request->query->get('kw');//type de poste 
        $city=$request->query->get('city');
       
if($form->isSubmitted() && $form->isValid() ){
        if (!empty($kw)) {
            $query = $this->getDoctrine()
                ->getManager()
                ->createQuery("select u from App:User u
                 where u.post = :kw and u.city= :city
                ")
                ->setParameter('kw', "$kw")
                ->setParameter('city', "$city");
            $users = $query->getResult();
        } else {
            $query = $this->getDoctrine()
                ->getManager()
                ->getRepository(User::class);
            $users = $query->findAll();
        }
 }
        return $this->render('default/index.html.twig',[
            'form' => $form->createView() 
        ]);

        //return $this->render('default/index.html.twig', compact('users'));
    }*/
    /**
     * @Route("/recherche", name="homepage")
     */
    public function indexAction(Request $request)
    {

        $kw = $request->query->get('kw');//type de service 
        $city=$request->query->get('city');//ville 
        if (!empty($kw)) {
            $query = $this->getDoctrine()
                ->getManager()
                ->createQuery("select u from App:User u
                 where u.post = :kw and u.city= :city
                ")
                ->setParameter('kw', "$kw")
                ->setParameter('city', "$city");
            $users = $query->getResult();
        } else {
            $query = $this->getDoctrine()
                ->getManager()
                ->getRepository(User::class);
            $users = $query->findAll();
        }


        return $this->render('default/index.html.twig', compact('users'));
    }
}

Desktop/ter_proximity/templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="form-group col-lg-6">
 


    

    <div class="row mt-3 d-flex justify-content-center">
        <form action="{{ path('homepage') }}" method="get">
               {{ form_start(form) }}
     {{ form_row(form.villeNom,{'attr':{'placeholder': "Type"}}) }}
    </div>
    
    <button type="submit" class="btn btn-primary">Enregistrer et passer à la suite</button>
    {{ form_end(form) }}


            <div class="row">
                <div class="col">
                    <input required type="text" name="city" class="form-control" id="city" placeholder="Ville">
                </div>
                <div class="col">
                    <input required type="text" name="kw" class="form-control" id="kw" placeholder="chercher">
                </div>
            </div>
            <div class="row my-2">
                <div class="col">
                    <label for="inputEmail4">Début</label>
                    <input required type="date" name="date1" class="form-control" id="d1" placeholder="Début">
                </div>
                <div class="col">
                    <label for="inputEmail4">Finir</label>
                    <input required type="date" name="date2" class="form-control" id="d2" placeholder="Finir">
                </div>
            </div>
{#            <div class="form-group mb-2">#}
{#                <label class="text-warning font-weight-bold sr-only" for="kw">Password</label>#}
{#                <input required type="text" name="city" class="form-control" id="city" placeholder="Ville">#}
{#                <div class="input-group-prepend">#}
{#                    <span class="glyphicon glyphicon-search"></span>#}
{#                </div>#}
{#            </div>#}
{#            <div class="form-group mb-2">#}
{#                <label class="text-warning font-weight-bold sr-only" for="kw">Password</label>#}
{#                <input required type="text" name="kw" class="form-control" id="kw" placeholder="chercher">#}
{#                <div class="input-group-prepend">#}
{#                    <span class="glyphicon glyphicon-search"></span>#}
{#                </div>#}
{#            </div>#}
{#            <div class="form-group mb-2">#}
{#                <label class="text-warning font-weight-bold sr-only" for="kw">Password</label>#}
{#                <input required type="date" name="date" class="form-control" id="city" placeholder="date">#}
{#                <div class="input-group-prepend">#}
{#                    <span class="glyphicon glyphicon-search"></span>#}
{#                </div>#}
{#            </div>#}
            <button type="submit" class="btn btn-primary mb-2">Rechercher</button>
        </form>
    </div>

    {% for user in users %}
        <div class="row mt-3">
            <div class="card mb-3 col-12">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img style="width: 70%" class="figure-img img-fluid rounded" src="{{ asset('image/avatar.jpg') }}" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body ">
                            <h5 class="card-title">{{ user.uuid }}</h5>
                            <p class="card-text">{{ user.email }}</p>
                            <p class="card-text">{{ user.password }}</p>
                            <p class="card-text"><small class="text-muted">Lundi -Samedi</small></p>
                            
                            <p class="card-text"><small class="text-muted">Fermé le dimanche</small></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    {% endfor %}


{% endblock %}